# OpenSpec agent integration files (skills, prompts, commands) for Pi and OpenCode.
#
# These files are checked into the repo at ./openspec-agent-files/ and copied
# to $out at build time. They were generated by `openspec init --tools pi,opencode --force`
# using openspec 1.4.1.
#
# To regenerate: rm -rf pkgs/openspec-agent-files && openspec init ... && cp ...
#
# Consumed by home-manager/openspec.nix to link individual files into
# global agent config directories (~/.pi/agent/ and ~/.config/opencode/).

{ runCommand }:

runCommand "openspec-agent-files-1.0" { } ''
  mkdir -p $out/.pi/skills $out/.pi/prompts
  mkdir -p $out/.opencode/skills $out/.opencode/commands
  cp -r ${./openspec-agent-files/.pi/skills}/* $out/.pi/skills/
  cp -r ${./openspec-agent-files/.pi/prompts}/* $out/.pi/prompts/
  cp -r ${./openspec-agent-files/.opencode/skills}/* $out/.opencode/skills/
  cp -r ${./openspec-agent-files/.opencode/commands}/* $out/.opencode/commands/
''
